name: Clang Tests

on:
  push:
    branches:
      - 'release/**'
    paths:
      - 'clang/**'
      - 'llvm/**'
      - '.github/workflows/clang-tests.yml'
  pull_request:
    paths:
      - 'clang/**'
      - 'llvm/**'
      - '.github/workflows/clang-tests.yml'

jobs:
  build_clang:
    name: clang check-all
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - macOS-latest
    steps:
    - name: Install Ninja
      uses: llvm/actions/install-ninja@master
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: ${{ matrix.cc }}-${{ matrix.version }}
    - name: Test clang
      uses: llvm/actions/build-test-llvm-project@master
      with:
        cmake_args: -G Ninja  -DLLVM_ENABLE_PROJECTS="clang" -DCMAKE_BUILD_TYPE=Release -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
        build_target: check-clang
